=== ilyapischyk/Task03/src/main/resources/file/gems.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/gems"
        xmlns:tns="http://www.example.com/gems"
        elementFormDefault="qualified">

    <element name="mineral" abstract="true"/>
    <element name="precious" type="tns:Precious" substitutionGroup="tns:mineral"/>
    <element name="semiprecious" type="tns:Semiprecious" substitutionGroup="tns:mineral"/>

    <element name="gems">
        <complexType>
            <sequence>
                <element ref="tns:mineral" minOccurs="16" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="AbstractGem">
        <sequence>
            <element name="visual-parameters" type="tns:VisualParameters"/>
            <element name="value" type="tns:Value"/>
            <element name="date-of-processing" type="date"/>
        </sequence>
        <attribute name="origin" type="tns:Origin"/>
    </complexType>

    <complexType name="VisualParameters">
        <sequence>
            <element name="color" type="string"/>
            <element name="transparency" type="tns:Transparency"/>
            <element name="cut" type="tns:Cut"/>
        </sequence>
    </complexType>

    <simpleType name="Value">
        <restriction base="string">
            <pattern value="([0-9]+)(.([0-9]+))?"/>
        </restriction>
    </simpleType>

    <simpleType name="Name">
        <restriction base="string">
            <pattern value="([a-zA-Z]{4,20})"/>
        </restriction>
    </simpleType>

    <simpleType name="Transparency">
        <restriction base="string">
            <pattern value="[0-9]||([1-9][0-9])||[100]"/>
        </restriction>
    </simpleType>

    <simpleType name="Cut">
        <restriction base="string">
            <pattern value="[1-9]||[1-8][0-9]"/>
        </restriction>
    </simpleType>

    <simpleType name="Origin">
        <restriction base="string">
            <pattern value="[A-Z][a-zA-Z]{2,30}"/>
        </restriction>
    </simpleType>

    <complexType name="Semiprecious">
        <complexContent>
            <extension base="tns:AbstractGem">
                <attribute name="name" type="tns:Name" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Precious">
        <complexContent>
            <extension base="tns:AbstractGem">
                <attribute name="name" use="optional" default="diamond">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="alexandrite"></enumeration>
                            <enumeration value="diamond"></enumeration>
                            <enumeration value="emerald"></enumeration>
                            <enumeration value="ruby"></enumeration>
                            <enumeration value="sapphire"></enumeration>
                            <enumeration value="chrysoberyl"></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== ilyapischyk/Task03/src/main/resources/file/gems.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.pischyk.com/funds gems.xsd">

    <semiprecious name="amethyst" origin="Germany">
        <visual-parameters>
            <color>purple</color>
            <transparency>26</transparency>
            <cut>5</cut>
        </visual-parameters>
        <value>5.7</value>
        <date-of-processing>2015-01-15</date-of-processing>
    </semiprecious>

    <semiprecious name="garnet" origin="Brazil">
        <visual-parameters>
            <color>red</color>
            <transparency>73</transparency>
            <cut>14</cut>
        </visual-parameters>
        <value>3.8</value>
        <date-of-processing>2019-05-04</date-of-processing>
    </semiprecious>

    <precious name="emerald" origin="Colombia">
        <visual-parameters>
            <color>green</color>
            <transparency>47</transparency>
            <cut>8</cut>
        </visual-parameters>
        <value>2.9</value>
        <date-of-processing>2021-02-12</date-of-processing>
    </precious>

    <semiprecious name="moonstone" origin="USA">
        <visual-parameters>
            <color>light blue</color>
            <transparency>19</transparency>
            <cut>4</cut>
        </visual-parameters>
        <value>4.2</value>
        <date-of-processing>2017-10-23</date-of-processing>
    </semiprecious>

    <semiprecious name="morganite" origin="China">
        <visual-parameters>
            <color>pink</color>
            <transparency>7</transparency>
            <cut>12</cut>
        </visual-parameters>
        <value>3.6</value>
        <date-of-processing>2014-06-10</date-of-processing>
    </semiprecious>

    <precious name="ruby" origin="Thailand">
        <visual-parameters>
            <color>red</color>
            <transparency>32</transparency>
            <cut>8</cut>
        </visual-parameters>
        <value>6.1</value>
        <date-of-processing>2016-02-29</date-of-processing>
    </precious>

    <precious name="sapphire" origin="India">
        <visual-parameters>
            <color>blue</color>
            <transparency>27</transparency>
            <cut>6</cut>
        </visual-parameters>
        <value>3.4</value>
        <date-of-processing>2020-11-11</date-of-processing>
    </precious>

    <semiprecious name="topaz" origin="USA">
        <visual-parameters>
            <color>yellow</color>
            <transparency>41</transparency>
            <cut>10</cut>
        </visual-parameters>
        <value>5.3</value>
        <date-of-processing>2020-04-03</date-of-processing>
    </semiprecious>

    <precious name="alexandrite" origin="Brazil">
        <visual-parameters>
            <color>purple</color>
            <transparency>60</transparency>
            <cut>14</cut>
        </visual-parameters>
        <value>3.9</value>
        <date-of-processing>2020-04-03</date-of-processing>
    </precious>

    <semiprecious name="quartz" origin="Russia">
        <visual-parameters>
            <color>colorless</color>
            <transparency>3</transparency>
            <cut>7</cut>
        </visual-parameters>
        <value>1.9</value>
        <date-of-processing>2018-02-04</date-of-processing>
    </semiprecious>

    <semiprecious name="opal" origin="Brazil">
        <visual-parameters>
            <color>blue</color>
            <transparency>55</transparency>
            <cut>4</cut>
        </visual-parameters>
        <value>2.7</value>
        <date-of-processing>2021-01-10</date-of-processing>
    </semiprecious>

    <semiprecious name="zircon" origin="USA">
        <visual-parameters>
            <color>brown</color>
            <transparency>86</transparency>
            <cut>11</cut>
        </visual-parameters>
        <value>4.0</value>
        <date-of-processing>2019-09-10</date-of-processing>
    </semiprecious>

    <semiprecious name="peridot" origin="Russia">
        <visual-parameters>
            <color>green</color>
            <transparency>50</transparency>
            <cut>13</cut>
        </visual-parameters>
        <value>2.2</value>
        <date-of-processing>2016-07-24</date-of-processing>
    </semiprecious>

    <semiprecious name="tourmaline" origin="China">
        <visual-parameters>
            <color>pink</color>
            <transparency>74</transparency>
            <cut>8</cut>
        </visual-parameters>
        <value>1.9</value>
        <date-of-processing>2011-02-05</date-of-processing>
    </semiprecious>

    <semiprecious name="rhodolite" origin="Russia">
        <visual-parameters>
            <color>purple</color>
            <transparency>52</transparency>
            <cut>6</cut>
        </visual-parameters>
        <value>3.3</value>
        <date-of-processing>2017-05-02</date-of-processing>
    </semiprecious>

    <semiprecious name="taaffeite" origin="Australia">
        <visual-parameters>
            <color>pink</color>
            <transparency>40</transparency>
            <cut>12</cut>
        </visual-parameters>
        <value>5.5</value>
        <date-of-processing>2019-03-26</date-of-processing>
    </semiprecious>
</gems>
